#!/usr/bin/env python3

"""Generates to stdout an assembly file to build all .s files in the programs/
directory. It optionally takes an explicit list of program names to include in
the output.

The assumptions are that each $(program).s file contains a public label called
$(program)_start that is the entry point for the program.

Example usage to generate programs.s from all programs in the programs/ directory:
  ./generate_programs_list.py > programs.s

Example usage to generate programs.s from just the snake and test programs in
the programs/ directory:
  ./generate_programs_list.py snake.s test.s > programs.s
"""

import os
import sys

FILE_HEADER = """; AUTOGENERATED FILE, DO NOT EDIT
        cpu 6301

        org $8000

; Program registry structure:
; - autorun address (run this on reset, 0 starts the monitor instead)
; - for each program:
;   - 2 bytes pointing at the next entry
;   - zero-terminated string with program name
;   - 2 bytes address for its entry point
; - after that a last entry with just a $0000 where the next entry address
;   would go

; Set to 0 to start in the monitor, otherwise runs this program at startup.
program_registry_autorun:"""

def generate_programs_s(programs):
    print(FILE_HEADER)
    print("        adr $0000")
    print("program_registry:")
    for program in programs:
        assert program.endswith(".s")
        basename = program[:-2]
        print("        adr +")
        print(f'        byt "{basename}\\0"')
        print(f"        adr {basename}_start")
        print("+")
    print("        adr $0000               ; End marker")
    print()
    for program in programs:
        print(f"        include programs/{program}")

if __name__ == "__main__":
    programs = []
    if len(sys.argv) == 1:
        # Make sure we can find the right programs directory regardless of where
        # the script is run.
        script_dir = os.path.dirname(os.path.abspath(__file__))
        programs_dir = os.path.join(script_dir, "programs")
        for filename in os.listdir(programs_dir):
            if filename.endswith(".s"):
                programs.append(filename)
    if len(sys.argv) > 1:
        programs = sys.argv[1:]
    generate_programs_s(sorted(programs))