#ifndef EIGHT_BITS_INSTRUCTIONS6301_H
#define EIGHT_BITS_INSTRUCTIONS6301_H

#include <array>
#include <cstdint>
#include <string>

namespace eight_bit {

enum AddressingMode {
  kIMM,  // 1-byte immediate
  kIM2,  // 2-byte immediate data
  kACA,
  kACB,
  kACD,
  kDIR,
  kDIRBIT,  // aim, oim, eim, tim
  kEXT,
  kIDX,
  kIDXBIT,  // aim, oim, eim, tim
  kIMP,
  kREL,
  kILL,  // Illegal instruction
};

struct Instruction {
  std::string name;
  uint8_t bytes;
  uint8_t cycles;
  AddressingMode mode;
};

constexpr std::array<Instruction, 256> kInstructions6301 = {
    Instruction{"", 0, 0, kILL},
    {"nop", 1, 1, kIMP},
    {"", 0, 0, kILL},
    {"", 0, 0, kILL},
    {"lsrd", 1, 1, kACD},
    {"asld", 1, 1, kACD},
    {"tap", 1, 1, kIMP},
    {"tpa", 1, 1, kIMP},
    {"inx", 1, 1, kIMP},
    {"dex", 1, 1, kIMP},
    {"clv", 1, 1, kIMP},
    {"sev", 1, 1, kIMP},
    {"clc", 1, 1, kIMP},
    {"sec", 1, 1, kIMP},
    {"cli", 1, 1, kIMP},
    {"sei", 1, 1, kIMP},
    {"sba", 1, 1, kACB},
    {"cba", 1, 1, kACB},
    {"", 0, 0, kILL},
    {"", 0, 0, kILL},
    {"", 0, 0, kILL},
    {"", 0, 0, kILL},
    {"tab", 1, 1, kACA},
    {"tba", 1, 1, kACB},
    {"xgdx", 1, 2, kIMP},
    {"", 0, 0, kILL},
    {"", 0, 0, kILL},
    {"aba", 1, 1, kACB},
    {"", 0, 0, kILL},
    {"", 0, 0, kILL},
    {"", 0, 0, kILL},
    {"", 0, 0, kILL},
    {"bra", 2, 3, kREL},
    {"brn", 2, 3, kREL},
    {"bhi", 2, 3, kREL},
    {"bls", 2, 3, kREL},
    {"bcc", 2, 3, kREL},
    {"bcs", 2, 3, kREL},
    {"bne", 2, 3, kREL},
    {"beq", 2, 3, kREL},
    {"bvc", 2, 3, kREL},
    {"bvs", 2, 3, kREL},
    {"bpl", 2, 3, kREL},
    {"bmi", 2, 3, kREL},
    {"bge", 2, 3, kREL},
    {"blt", 2, 3, kREL},
    {"bgt", 2, 3, kREL},
    {"ble", 2, 3, kREL},
    {"tsx", 1, 1, kIMP},
    {"ins", 1, 1, kIMP},
    {"pula", 1, 3, kIMP},
    {"pulb", 1, 3, kIMP},
    {"des", 1, 1, kIMP},
    {"txs", 1, 1, kIMP},
    {"psha", 1, 4, kACA},
    {"pshb", 1, 4, kACB},
    {"pulx", 1, 4, kIMP},
    {"rts", 1, 5, kIMP},
    {"abx", 1, 1, kIMP},
    {"rti", 1, 10, kIMP},
    {"pshx", 1, 5, kIMP},
    {"mul", 1, 7, kIMP},
    {"", 0, 0, kILL},
    {"", 0, 0, kILL},
    {"nega", 1, 1, kACA},
    {"", 0, 0, kILL},
    {"", 0, 0, kILL},
    {"coma", 1, 1, kACA},
    {"lsra", 1, 1, kACA},
    {"", 0, 0, kILL},
    {"rora", 1, 1, kACA},
    {"asra", 1, 1, kACA},
    {"asla", 1, 1, kACA},
    {"rola", 1, 1, kACA},
    {"deca", 1, 1, kACA},
    {"", 0, 0, kILL},
    {"inca", 1, 1, kACA},
    {"tsta", 1, 1, kACA},
    {"", 0, 0, kILL},
    {"clra", 1, 1, kACA},
    {"negb", 1, 1, kACB},
    {"", 0, 0, kILL},
    {"", 0, 0, kILL},
    {"comb", 1, 1, kACB},
    {"lsrb", 1, 1, kACB},
    {"", 0, 0, kILL},
    {"rorb", 1, 1, kACB},
    {"asrb", 1, 1, kACB},
    {"aslb", 1, 1, kACB},
    {"rolb", 1, 1, kACB},
    {"decb", 1, 1, kACB},
    {"", 0, 0, kILL},
    {"incb", 1, 1, kACB},
    {"tstb", 1, 1, kACB},
    {"", 0, 0, kILL},
    {"clrb", 1, 1, kACB},
    {"neg", 2, 6, kIDX},
    {"aim", 3, 7, kIDXBIT},
    {"oim", 3, 7, kIDXBIT},
    {"com", 2, 6, kIDX},
    {"lsr", 2, 6, kIDX},
    {"eim", 3, 7, kIDXBIT},
    {"ror", 2, 6, kIDX},
    {"asr", 2, 6, kIDX},
    {"asl", 2, 6, kIDX},
    {"rol", 2, 6, kIDX},
    {"dec", 2, 6, kIDX},
    {"tim", 3, 7, kIDXBIT},
    {"inc", 2, 6, kIDX},
    {"tst", 2, 4, kIDX},
    {"jmp", 2, 3, kIDX},
    {"clr", 2, 5, kIDX},
    {"neg", 3, 6, kEXT},
    {"aim", 3, 6, kDIRBIT},
    {"oim", 3, 6, kDIRBIT},
    {"com", 3, 6, kEXT},
    {"lsr", 3, 6, kEXT},
    {"eim", 3, 6, kDIRBIT},
    {"ror", 3, 6, kEXT},
    {"asr", 3, 6, kEXT},
    {"asl", 3, 6, kEXT},
    {"rol", 3, 6, kEXT},
    {"dec", 3, 6, kEXT},
    {"tim", 3, 6, kDIRBIT},
    {"inc", 3, 6, kEXT},
    {"tst", 3, 4, kEXT},
    {"jmp", 3, 3, kEXT},
    {"clr", 3, 5, kEXT},
    {"suba", 2, 2, kIMM},
    {"cmpa", 2, 2, kIMM},
    {"sbca", 2, 2, kIMM},
    {"subd", 3, 3, kIM2},
    {"anda", 2, 2, kIMM},
    {"bita", 2, 2, kIMM},
    {"ldaa", 2, 2, kIMM},
    {"", 0, 0, kILL},
    {"eora", 2, 2, kIMM},
    {"adca", 2, 2, kIMM},
    {"oraa", 2, 2, kIMM},
    {"adda", 2, 2, kIMM},
    {"cpx", 3, 3, kIM2},
    {"bsr", 2, 5, kIMM},
    {"lds", 3, 3, kIM2},
    {"", 0, 0, kILL},
    {"suba", 2, 3, kDIR},
    {"cmpa", 2, 3, kDIR},
    {"sbca", 2, 3, kDIR},
    {"subd", 2, 4, kDIR},
    {"anda", 2, 3, kDIR},
    {"bita", 2, 3, kDIR},
    {"ldaa", 2, 3, kDIR},
    {"staa", 2, 3, kDIR},
    {"eora", 2, 3, kDIR},
    {"adca", 2, 3, kDIR},
    {"oraa", 2, 3, kDIR},
    {"adda", 2, 3, kDIR},
    {"cpx", 2, 4, kDIR},
    {"jsr", 2, 5, kDIR},
    {"lds", 2, 4, kDIR},
    {"sts", 2, 4, kDIR},
    {"suba", 2, 4, kIDX},
    {"cmpa", 2, 4, kIDX},
    {"sbca", 2, 4, kIDX},
    {"subd", 2, 5, kIDX},
    {"anda", 2, 4, kIDX},
    {"bita", 2, 4, kIDX},
    {"ldaa", 2, 4, kIDX},
    {"staa", 2, 4, kIDX},
    {"eora", 2, 4, kIDX},
    {"adca", 2, 4, kIDX},
    {"oraa", 2, 4, kIDX},
    {"adda", 2, 4, kIDX},
    {"cpx", 2, 5, kIDX},
    {"jsr", 2, 5, kIDX},
    {"lds", 2, 5, kIDX},
    {"sts", 2, 5, kIDX},
    {"suba", 3, 4, kEXT},
    {"cmpa", 3, 4, kEXT},
    {"sbca", 3, 4, kEXT},
    {"subd", 3, 5, kEXT},
    {"anda", 3, 4, kEXT},
    {"bita", 3, 4, kEXT},
    {"ldaa", 3, 4, kEXT},
    {"staa", 3, 4, kEXT},
    {"eora", 3, 4, kEXT},
    {"adca", 3, 4, kEXT},
    {"oraa", 3, 4, kEXT},
    {"adda", 3, 4, kEXT},
    {"cpx", 3, 5, kEXT},
    {"jsr", 3, 6, kEXT},
    {"lds", 3, 5, kEXT},
    {"sts", 3, 5, kEXT},
    {"subb", 2, 2, kIMM},
    {"cmpb", 2, 2, kIMM},
    {"sbcb", 2, 2, kIMM},
    {"addd", 3, 3, kIM2},
    {"andb", 2, 2, kIMM},
    {"bitb", 2, 2, kIMM},
    {"ldab", 2, 2, kIMM},
    {"", 0, 0, kILL},
    {"eorb", 2, 2, kIMM},
    {"adcb", 2, 2, kIMM},
    {"orab", 2, 2, kIMM},
    {"addb", 2, 2, kIMM},
    {"ldd", 3, 3, kIM2},
    {"", 0, 0, kILL},
    {"ldx", 3, 3, kIM2},
    {"", 0, 0, kILL},
    {"subb", 2, 3, kDIR},
    {"cmpb", 2, 3, kDIR},
    {"sbcb", 2, 3, kDIR},
    {"addd", 2, 4, kDIR},
    {"andb", 2, 3, kDIR},
    {"bitb", 2, 3, kDIR},
    {"ldab", 2, 3, kDIR},
    {"stab", 2, 3, kDIR},
    {"eorb", 2, 3, kDIR},
    {"adcb", 2, 3, kDIR},
    {"orab", 2, 3, kDIR},
    {"addb", 2, 3, kDIR},
    {"ldd", 2, 4, kDIR},
    {"std", 2, 4, kDIR},
    {"ldx", 2, 4, kDIR},
    {"stx", 2, 4, kDIR},
    {"subb", 2, 4, kIDX},
    {"cmpb", 2, 4, kIDX},
    {"sbcb", 2, 4, kIDX},
    {"addd", 2, 5, kIDX},
    {"andb", 2, 4, kIDX},
    {"bitb", 2, 4, kIDX},
    {"ldab", 2, 4, kIDX},
    {"stab", 2, 4, kIDX},
    {"eorb", 2, 4, kIDX},
    {"adcb", 2, 4, kIDX},
    {"orab", 2, 4, kIDX},
    {"addb", 2, 4, kIDX},
    {"ldd", 2, 5, kIDX},
    {"std", 2, 5, kIDX},
    {"ldx", 2, 5, kIDX},
    {"stx", 2, 5, kIDX},
    {"subb", 3, 4, kEXT},
    {"cmpb", 3, 4, kEXT},
    {"sbcb", 3, 4, kEXT},
    {"addd", 3, 5, kEXT},
    {"andb", 3, 4, kEXT},
    {"bitb", 3, 4, kEXT},
    {"ldab", 3, 4, kEXT},
    {"stab", 3, 4, kEXT},
    {"eorb", 3, 4, kEXT},
    {"adcb", 3, 4, kEXT},
    {"orab", 3, 4, kEXT},
    {"addb", 3, 4, kEXT},
    {"ldd", 3, 5, kEXT},
    {"std", 3, 5, kEXT},
    {"ldx", 3, 5, kEXT},
    {"stx", 3, 5, kEXT}};

}  // namespace eight_bit

#endif  // EIGHT_BITS_INSTRUCTIONS6301_H